# Generated by Django 5.2.5 on 2025-08-14 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('SAINS', 'Sains & Teknologi'), ('SOSPOL', 'Sosial & Politik'), ('EKONOMI', 'Ekonomi'), ('ETIKA', 'Etika & Filsafat'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Debat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Lawan'), ('BERLANGSUNG', 'Sedang Berlangsung'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pengguna_kontra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debat_kontra', to=settings.AUTH_USER_MODEL)),
                ('pengguna_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debat_pro', to=settings.AUTH_USER_MODEL)),
                ('mosi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debat.mosi')),
            ],
        ),
        migrations.CreateModel(
            name='Argumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klaim', models.TextField()),
                ('bukti', models.TextField()),
                ('jaminan', models.TextField()),
                ('ronde', models.IntegerField(default=1)),
                ('dikirim_pada', models.DateTimeField(auto_now_add=True)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('debat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debat.debat')),
            ],
        ),
    ]
