# Generated by Django 5.2.5 on 2025-08-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debat', '0003_debat_max_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedfallacy',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
