# Generated by Django 5.2.5 on 2025-08-15 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaggedFallacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debat.argumen')),
                ('fallacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debat.fallacy')),
                ('tagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('argument', 'fallacy', 'tagged_by')},
            },
        ),
    ]
