# Generated by Django 5.2.5 on 2025-08-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debat', '0002_fallacy_taggedfallacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='debat',
            name='max_rounds',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
